server {
    listen 80;
    server_name expenses.alija-rai.com.np 10.120.97.51;



    location / {
        root /var/www/html/Expenses-Tracking-Frontend;
        index index.html;
        try_files $uri /index.html;
    }


    location /static/ {
        alias /home/deployuser/project/expenses-tracking-backend/staticfiles/;
    }


    location /api/ {
        proxy_pass http://unix:/home/deployuser/project/expenses-tracking-backend/gunicorn.sock; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}

